# Lightweight Edge Agent
# Connects back to main IT management server

services:
  ##########
  # Portainer Agent - Connects to main Portainer server
  #
  portainer-agent:
    image: portainer/agent:${PORTAINER_TAG:-latest}
    container_name: portainer-agent
    restart: unless-stopped
    networks:
      - portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      AGENT_SECRET: ${PORTAINER_AGENT_SECRET}
    ports:
      - "${PORTAINER_AGENT_PORT:-9001}:9001"
  #
  ##########

  ##########
  # Watchtower - Automatic container updates
  #
  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_TAG:-latest}
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ:-UTC}
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_REVIVE_STOPPED: "false"
      WATCHTOWER_SCHEDULE: "0 2 * * *"  # 2 AM daily
    command: --interval 86400 --cleanup
  #
  ##########

networks:
  portainer-agent:
    driver: bridge
