##############################
# NETWORKS
#
networks:
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/27
#
##############################

##############################
# SERVICES
#
services:
  ####################
  # SECURITY
  #
  ##########
  # Docker Socket Proxy - Security Enchanced Proxy for Docker Socket
  #
  socket-proxy:
    image: tecnativa/docker-socket-proxy:${SOCKET_PROXY_TAG:-latest}
    container_name: socket-proxy
    #profiles: ["security"]
    restart: always
    healthcheck:
      test: wget --spider http://localhost:2375/version || exit 1
      interval: "29s"
      timeout: "5s"
      retries: 3
      start_period: "21s"
    privileged: true
    security_opt:
      - no-new-privileges:true
    networks:
      - socket_proxy
        #ipv4_address: 172.15.2.1 # You can specify a static IP
    ports:
      - "127.0.0.1:${SOCKET_PROXY_PORT:-2375}:2375" # Port 2375 should only ever get exposed to the internal network. When possible use this line.
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ}
      LOG_LEVEL: info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      EVENTS: 1
      PING: 1
      VERSION: 1
      ## Revoked by Default
      # SecurGity critical
      AUTH: 0
      SECRETS: 0
      POST: 1 # Ouroboros=1
      # Not always needed
      BUILD: 0
      COMMIT: 0
      CONFIGS: 0
      CONTAINERS: 1 # Portainer, etc.
      DISTRIBUTION: 0
      EXEC: 0
      IMAGES: 1 # Portainer
      INFO: 1 # Portainer
      NETWORKS: 1 # Portainer
      NODES: 0
      PLUGINS: 0
      SERVICES: 1 # Portainer
      SESSION: 0
      SWARM: 0
      SYSTEM: 0
      TASKS: 1 # Portaienr
      VOLUMES: 1 # Portainer
    #labels:
  #
  ##########
  #
  ####################
#
############################## 
