##############################
# SERVICES
#
services:
  ####################
  # LOG MGMT
  #
  ##########
  # Dozzle - Real-time Docker Log Viewer
  #
  dozzle:
    image: amir20/dozzle:${DOZZLE_TAG:-latest}
    container_name: dozzle
    profiles: ["observability", "debug"]
    depends_on:
      socket-proxy:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    networks:
      - socket_proxy
    ports:
      - ${DOZZLE_PORT:-8080}:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: ${TZ:-UTC}
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
      # DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label
      DOCKER_HOST: tcp://socket-proxy:${SOCKET_PROXY_PORT:-2375}
    #labels:
  #
  ##########
  #
  ####################
#
##############################
