##############################
# NETWORKS
#
networks:
  portainer:
    name: portainer_agent_network
#
##############################

##############################
# SERVICES
#
services:
  ######################
  # CONTAINER MGMT
  #
  ##########
  # Portainer - WebUI for Containers
  #
  portainer:
    image: portainer/portainer-ce:${PORTAINER_TAG:-latest}
    container_name: portainer
    profiles: ["container_management"]
    depends_on:
      socket-proxy:
        condition: service_healthy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
      - socket_proxy
    ports:
      - ${PORTAINER_PORT:-9000}:9000
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock:ro # # Use Docker Socket Proxy instead for improved security
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    environment:
      TZ: ${TZ}
      DOCKER_HOST: tcp://socket-proxy:${SOCKET_PROXY_PORT:-2375}
    #labels:
  #
  ##########

  ##########
  # Portainer Agent
  #
  portainer_agent:
    image: portainer/agent:${PORTAINER_TAG:-latest}
    #profiles: ["container_management"]
    profiles: ["container_management_agent"]
    container_name: portainer_agent
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - portainer
    ports:
      - ${PORTAINER_AGENT_PORT:-9001}:9001/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_VOLUMES:-/var/lib/docker/volumes}:/var/lib/docker/volumes
      - /:/host
    environment:
      TZ: ${TZ}
  #
  ##########
  #
  ####################
#
##############################
