name: Security Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security check
      run: |
        chmod +x ./scripts/security_check.sh
        ./scripts/security_check.sh
        
    - name: Check for secrets in commits
      run: |
        # Check if any secrets might be exposed
        if grep -r -E "(password|secret|key|token|api).*(=|:).+[a-zA-Z0-9]{8,}" . --exclude-dir=.git --exclude="*.example" --exclude="*.md" | grep -v "file:///run/secrets/" | grep -v "_FILE:"; then
          echo "❌ Potential secrets found in files"
          exit 1
        else
          echo "✅ No secrets detected"
        fi
        
    - name: Validate Docker Compose files
      run: |
        # Check if docker-compose files are valid
        # Detect docker compose command
        if command -v docker-compose >/dev/null 2>&1; then
          DOCKER_COMPOSE_CMD="docker-compose"
        elif docker compose version >/dev/null 2>&1; then
          DOCKER_COMPOSE_CMD="docker compose"
        else
          echo "❌ Neither docker-compose nor docker compose is available"
          exit 1
        fi
        
        echo "Using Docker Compose command: $DOCKER_COMPOSE_CMD"
        
        # Validate main docker-compose.yml (which includes all services)
        if [ -f "docker-compose.yml" ]; then
          echo "Validating main docker-compose.yml"
          $DOCKER_COMPOSE_CMD config > /dev/null
          echo "✅ Main docker-compose.yml is valid"
        fi
        
        # Skip individual service compose files as they require main environment
        
    - name: Check for required files
      run: |
        # Ensure critical files exist
        required_files=(".env.example" "README.md" "SECRETS_SETUP.md" "Makefile")
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ Required file missing: $file"
            exit 1
          fi
        done
        echo "✅ All required files present"
